# Generated by Django 3.2.6 on 2021-08-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Work',
        ),
    ]
