# Generated by Django 3.2.6 on 2021-08-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employee_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='employee_name',
            new_name='emp_name',
        ),
    ]
