# Generated by Django 3.2.6 on 2021-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('doctor_time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Onduty', 'Onduty'), ('Offduty', 'Offduty'), ('Available', 'Available')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('doctor_time', models.IntegerField()),
                ('doctor_fee', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
