# Generated by Django 3.2.6 on 2021-09-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0003_remove_appointment_doctor_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
