# Generated by Django 3.2.6 on 2021-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0004_auto_20210924_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('Female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
