# Generated by Django 3.2.6 on 2021-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_batch_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('topic_status', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed')], default='in progress', max_length=100)),
            ],
        ),
    ]
