# Generated by Django 3.2.6 on 2021-09-10 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20210909_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 9, 15), null=True),
        ),
    ]
