# Generated by Django 3.2.6 on 2021-09-11 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 9, 16), null=True),
        ),
    ]
